### ISSUE TITLE
Build issue with Netlify

### ISSUE THREAD

**Issue by msrajput8894** [msrajput8894/Javascript-course#1]
Not able to build the project at Netlify due to Parcel/Watcher problem.

Getting following error.
Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-x64-glibc. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher. 12:38:22 AM: at Object.<anonymous> (/opt/build/repo/node_modules/@parcel/watcher/index.js:26:13) 12:38:22 AM: at Module._compile (node:internal/modules/cjs/loader:1364:14) 12:38:22 AM: at Module._extensions..js (node:internal/modules/cjs/loader:1422:10) 12:38:22 AM: at Module.load (node:internal/modules/cjs/loader:1203:32) 12:38:22 AM: at Module._load (node:internal/modules/cjs/loader:1019:12) 12:38:22 AM: at Module.require (node:internal/modules/cjs/loader:1231:19) 12:38:22 AM: at require (node:internal/modules/helpers:177:18) 12:38:22 AM: at Object.<anonymous> (/opt/build/repo/node_modules/@parcel/fs/lib/index.js:9:28) 12:38:22 AM: at Module._compile (node:internal/modules/cjs/loader:1364:14) 12:38:22 AM: at Module._extensions..js (node:internal/modules/cjs/loader:1422:10) 12:38:23 AM: ​12:38:23 AM: "build.command" failed 12:38:23 AM: ──────────────────────────────────────────────────────────────── 12:38:23 AM: ​12:38:23 AM: Error message 12:38:23 AM: Command failed with exit code 1: parcel build index.html --dist-dir ./dist (https://ntl.fyi/exit-code-1) 12:38:23 AM: ​12:38:23 AM: Error location 12:38:23 AM: In Build command from Netlify app: 12:38:23 AM: parcel build index.html --dist-dir ./dist 12:38:23 AM: ​12:38:23 AM: Resolved config 12:38:23 AM: build: 12:38:23 AM: command: parcel build index.html --dist-dir ./dist 12:38:23 AM: commandOrigin: ui 12:38:23 AM: publish: /opt/build/repo/dist 12:38:23 AM: publishOrigin: ui 12:38:23 AM: Build failed due to a user error: Build script returned non-zero exit code: 2 12:38:23 AM: Failing build: Failed to build site 12:38:23 AM: Finished processing build request in 22.33s

**Comment by msrajput8894** [comment]
Re-installed parcel latest version, also installed parcel/watcher and re-installed all dependencies from package.json which helped to resolve the issue
